name: CD Sandbox - Terraform Apply

on:
  push:
    branches:
      - sandbox
  workflow_dispatch:

permissions:
  contents: read

env:
  TF_WORKING_DIR: terraform
  TF_VAR_FILE: env/sandbox.tfvars
  TF_BACKEND_KEY: github-actions-cicd/sandbox/terraform.tfstate

jobs:
  terraform-apply:
    name: Terraform Apply - Sandbox
    runs-on: ubuntu-latest
    environment: sandbox

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: AKIARBGLDDCFDRMITRAU
          aws-secret-access-key: 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
          aws-region: us-east-1

      - name: Terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init -backend-config="key=${{ env.TF_BACKEND_KEY }}"

      - name: Terraform validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform validate

      - name: Terraform apply
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -var-file=${{ env.TF_VAR_FILE }} -auto-approve

