name: CI QA - Terraform Plan

on:
  pull_request:
    branches:
      - qa
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: read

env:
  TF_WORKING_DIR: terraform
  TF_VAR_FILE: env/qa.tfvars
  TF_BACKEND_KEY: github-actions-cicd/qa/terraform.tfstate

jobs:
  terraform-plan:
    name: Terraform Plan - QA
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::333333333333:role/GitHubActionsTerraformQARole
          aws-region: us-east-1

      - name: Terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init -backend-config="key=${{ env.TF_BACKEND_KEY }}"

      - name: Terraform validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform validate

      - name: Terraform plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan -var-file=${{ env.TF_VAR_FILE }} -no-color

